# ChangeSkin config

# Here you can specify default skins for player who do not have a skin
# The entries from this list will be selected in random order
#
# Lists are created like this:
#default-skins:
#    - 0aaa2c13-922a-411b-b655-9b8c08404695
#    - 069a79f4-44e9-4726-a5be-fca90e38aaf5
#
# If this list is empty no skin will be selected
default-skins: []

# If the player does not have a skin and hasn't chosen one with /setskin
# this will try to redownload using the username of the player
restoreSkins: false

# Should the skins apply instantly without relogins
# The player will be invisible for a shorten time
instantSkinChange: true